### ISSUE TITLE
Bug with pug filename

### ISSUE THREAD

**Issue by ismay** [metalsmith/metalsmith-in-place#158]
Pug needs a filename to be set, but only picks it up when it's in the engineOptions, and not the locals. See https://github.com/greenthewizard/metalsmith-test-1/pull/1. Check whether this would be an issue for layouts as well.

**Comment by jmatsushita** [comment]
Also came across this limitation. 👍

**Comment by ismay** [comment]
So for pug the filename prop should be set in options. I think we'd have to solve this from in-place itself (maybe layouts as well, although I don't think so since there the template is read from disk, not memory).

**Comment by ismay** [comment]
This should work now, published a new feature in 4.4.0 called `setFilename`, which will pass the required info. Don't know if there are templating engines that require a different prop (like `path` or something), but we can add those later if necessary.
